In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv("homework_4_files/course_lead_scoring_2026.csv")

In [3]:
df

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
...,...,...,...,...,...,...,...,...,...
4995,organic_search,education,employed,asia,45834.0,2,2,0.37,1
4996,NaN,technology,employed,north_america,84831.0,2,5,0.51,0
4997,organic_search,finance,employed,asia,53636.0,4,6,0.75,1
4998,referral,technology,employed,africa,69430.0,4,8,0.79,1
4999,referral,technology,employed,europe,81355.0,6,11,0.99,1

## Data preparation

In [4]:
categorical = ['lead_source', 'industry', 'employment_status', 'location']
numerical = ['annual_income', 'number_of_courses_viewed', 'interaction_count', 'lead_score']

In [5]:
for col in categorical:
    print(col)
    print(df[col].isna().sum())

lead_source
148
industry
240
employment_status
194
location
208

In [24]:
for col in categorical:
    df[col] = df[col].fillna('NA')

In [7]:
for col in numerical:
    print(col)
    print(df[col].isna().sum())

annual_income
369
number_of_courses_viewed
0
interaction_count
0
lead_score
35

In [23]:
for col in numerical:
    df[col] = df[col].fillna(0.0)

In [9]:
from sklearn.model_selection import train_test_split

In [25]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=1
)

In [26]:
y_full_train = df_full_train["converted"]
y_test = df_test["converted"]
y_train = df_train["converted"]
y_val = df_val["converted"]

In [27]:
del df_full_train["converted"]
del df_train["converted"]
del df_val["converted"]
del df_test["converted"]

## Question 1

In [19]:
from sklearn.metrics import roc_auc_score

In [28]:
df_train[numerical]

      annual_income  number_of_courses_viewed  interaction_count  lead_score
4740        80198.0                         5                  9        0.91
1452        50548.0                         2                  5        0.48
2846        76300.0                         0                  3        0.42
4670        80371.0                         2                  6        0.49
168         73567.0                         2                  4        0.48
...             ...                       ...                ...         ...
253         84573.0                         2                  3        0.37
1366        85051.0                         1                  3        0.56
753         21561.0                         0                  1        0.17
4990        31691.0                         3                  5        0.49
357         46342.0                         5                  9        0.85

[3000 rows x 4 columns]

In [30]:
for col in numerical:
    print(col)
    print(roc_auc_score(y_train, df_train[col]))
    print()

annual_income
0.6081977776250831

number_of_courses_viewed
0.7229894623989618

interaction_count
0.7649203047563227

lead_score
0.7882254810906102

lead_score has the highest AUC. <br>Note that none of the scores were less than 0.5

## Question 2