In [1]:
import pandas as pd
import numpy as np

## Pandas version

In [2]:
pd.__version__

'3.0.6'

In [3]:
df = pd.read_csv(r"homework_1_files/car_fuel_efficiency_2026.csv")

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

## Records count

In [5]:
len(df)

10000

## Fuel types

In [6]:
len(df["fuel_type"].unique())

3

## Missing values

In [7]:
df.isna().any().sum()

np.int64(2)

## Max fuel efficiency

In [8]:
df.loc[df["origin"]=="Asia"]["fuel_efficiency_mpg"].max()

np.float64(41.2)

## Median value of horsepower

In [9]:
df['horsepower'].median()

np.float64(254.0)

In [10]:
most_freq_value = df['horsepower'].value_counts().index[0]
print(most_freq_value)

252.0

In [11]:
df['horsepower'] = df['horsepower'].fillna(most_freq_value)

In [12]:
df['horsepower'].median()

np.float64(252.0)

Decreased.

## Sum of weights

In [13]:
res = df.loc[(df['origin'] == 'Asia')][['vehicle_weight', 'model_year']].head(7)
res

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [29]:
x = res.to_numpy()
x

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [30]:
x.T

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [48]:
xtx = x.T.dot(x)

In [49]:
xtx

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [50]:
xtx_inv = np.linalg.inv(xtx)
xtx_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [57]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [55]:
w = xtx_inv.dot(x.T)
w

array([[-2.50082897e-04, -1.65786806e-05, -2.86196661e-04,
         3.99964853e-04, -1.18162927e-03,  1.10298508e-03,
         2.25354894e-04],
       [ 6.12974614e-04,  1.06954785e-04,  6.91249245e-04,
        -7.95968736e-04,  2.63152339e-03, -2.31749941e-03,
        -4.16221392e-04]])

In [61]:
res = w.dot(y)
res

array([0.13644777, 0.2327492 ])

In [62]:
res.sum()

np.float64(0.36919696904925486)