In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
from sklearn.metrics import mutual_info_score

In [3]:
ls

'Homework 1.ipynb'  'Homework 3.ipynb'   homework_1_files/   homework_3_files/
'Homework 2.ipynb'   README.md           homework_2_files/   venv/

In [4]:
df = pd.read_csv("homework_3_files/course_lead_scoring_2026.csv")

In [5]:
df

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
...,...,...,...,...,...,...,...,...,...
4995,organic_search,education,employed,asia,45834.0,2,2,0.37,1
4996,NaN,technology,employed,north_america,84831.0,2,5,0.51,0
4997,organic_search,finance,employed,asia,53636.0,4,6,0.75,1
4998,referral,technology,employed,africa,69430.0,4,8,0.79,1
4999,referral,technology,employed,europe,81355.0,6,11,0.99,1

## Data preparation

In [6]:
for col in df.columns[df.isna().any()].tolist():
    print(f"{col} : {df[col].dtype}")

lead_source : str
industry : str
employment_status : str
location : str
annual_income : float64
lead_score : float64

In [7]:
for col in df.columns[df.isna().any()].tolist():
    temptype = df[col].dtype
    if temptype == str:
        df[col] = df[col].fillna("NA")
    else:
        df[col] = df[col].fillna(0)

# note : sample of df was observed with actual values as well.
# Merely having int or float dtype does not ensure that the column represents numerical feature

In [8]:
df.isna().any()

lead_source                 False
industry                    False
employment_status           False
location                    False
annual_income               False
number_of_courses_viewed    False
interaction_count           False
lead_score                  False
converted                   False
dtype: bool

## Question 1

In [9]:
df['industry'].value_counts().index[0]

'technology'

Technology

## Question 2

In [10]:
# note - question can be answered by considering all columns with int or string dtype, 
# which may/may not be numerical features

In [11]:
print(df[["interaction_count"]].corrwith(df["lead_score"]).abs().values[0])
print(df[["number_of_courses_viewed"]].corrwith(df["lead_score"]).abs().values[0])
print(df[["number_of_courses_viewed"]].corrwith(df["interaction_count"]).abs().values[0])
print(df[["annual_income"]].corrwith(df["interaction_count"]).abs().values[0])

0.9157457980418677
0.7572042392104888
0.7216090038937009
0.12284235135955954

interaction_count and lead_score have biggest correlation.

## Question 3

In [12]:
# df_original = df.copy()
# df.drop("converted", axis=1, inplace=True)

In [13]:
# df_original.columns

In [14]:
df.columns

Index(['lead_source', 'industry', 'employment_status', 'location',
       'annual_income', 'number_of_courses_viewed', 'interaction_count',
       'lead_score', 'converted'],
      dtype='str')

In [15]:
for col in df.columns:
    temptype = df[col].dtype
    if temptype == "object":
        # print(col)
        # print(df[col].value_counts())
        # print("----")
        df[col] = df[col].astype(str)
    # print(df[col].dtype)

In [16]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=42
)

In [17]:
y_full_train = df_full_train["converted"]
y_test = df_test["converted"]
y_train = df_train["converted"]
y_val = df_val["converted"]

In [18]:
del df_full_train["converted"]
del df_train["converted"]
del df_val["converted"]
del df_test["converted"]

In [19]:
# for col in df_full_train:
#     print(col, end = ": ")
#     print(mutual_info_score(df_full_train[col], df_original

In [20]:
print(df["lead_source"].value_counts())

lead_source
organic_search    1251
paid_ads          1140
social_media      1055
referral           790
events             616
0                  148
Name: count, dtype: int64

In [21]:
for col in df_full_train.columns:
    if df_full_train[col].dtype != "str":
        continue
    #     df_full_train[col] = pd.to_categorical(df_full_train[col])
    print(col, end = ": ")
    print(round(mutual_info_score(df_full_train[col], y_full_train),2))

lead_source: 0.03
industry: 0.0
employment_status: 0.02
location: 0.0

lead_source

## Question 4

In [22]:
# identify categorical columns
for col in df.columns:
    print(col)
    print(df[col].nunique())
    print(df[col].value_counts())
    print()

lead_source
6
lead_source
organic_search    1251
paid_ads          1140
social_media      1055
referral           790
events             616
0                  148
Name: count, dtype: int64

industry
7
industry
technology       1173
retail            925
healthcare        840
finance           720
education         639
manufacturing     463
0                 240
Name: count, dtype: int64

employment_status
5
employment_status
employed         2633
student           760
self_employed     715
unemployed        698
0                 194
Name: count, dtype: int64

location
6
location
north_america    1371
europe           1149
asia             1052
south_america     749
africa            471
0                 208
Name: count, dtype: int64

annual_income
4314
annual_income
0.0        369
12000.0    185
63098.0      3
53198.0      3
61452.0      3
          ...
45834.0      1
84831.0      1
53636.0      1
69430.0      1
81355.0      1
Name: count, Length: 4314, dtype: int64

number_of_courses_viewed
7
number_of_courses_viewed
2    1659
3    1212
1    1083
0     474
4     459
5     104
6       9
Name: count, dtype: int64

interaction_count
14
interaction_count
4     800
5     798
6     653
3     644
2     492
7     476
1     325
0     283
8     259
9     146
10     82
11     31
12      8
13      3
Name: count, dtype: int64

lead_score
100
lead_score
0.46    114
0.48    112
0.47    104
0.53    104
0.60    104
       ...
0.05      5
0.97      5
0.03      5
0.95      5
0.98      3
Name: count, Length: 100, dtype: int64

converted
2
converted
1    2883
0    2117
Name: count, dtype: int64

In [23]:
df

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,0,0.0,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
...,...,...,...,...,...,...,...,...,...
4995,organic_search,education,employed,asia,45834.0,2,2,0.37,1
4996,0,technology,employed,north_america,84831.0,2,5,0.51,0
4997,organic_search,finance,employed,asia,53636.0,4,6,0.75,1
4998,referral,technology,employed,africa,69430.0,4,8,0.79,1
4999,referral,technology,employed,europe,81355.0,6,11,0.99,1

In [24]:
categorical = [x for x in df.columns if df[x].dtype == 'str']
categorical

['lead_source', 'industry', 'employment_status', 'location']

In [25]:
numerical = [x for x in df.columns if df[x].dtype != 'str' and x != 'converted']
numerical

['annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score']

### One hot encoding

In [26]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient = 'records')
X_train = dv.fit_transform(train_dict)

In [27]:
val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [28]:
df_train

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score
4702,paid_ads,finance,employed,asia,65980.0,2,3,0.37
2155,events,finance,employed,south_america,71662.0,0,0,0.09
289,referral,0,employed,asia,40220.0,2,5,0.55
1822,organic_search,finance,employed,north_america,88352.0,2,2,0.45
3442,events,technology,employed,north_america,89316.0,1,5,0.00
...,...,...,...,...,...,...,...,...
3200,paid_ads,finance,employed,asia,81522.0,1,3,0.29
617,social_media,retail,employed,asia,33075.0,1,1,0.30
1992,organic_search,finance,employed,africa,71532.0,3,5,0.58
3301,social_media,retail,employed,asia,48836.0,0,0,0.03
3687,paid_ads,finance,employed,asia,68969.0,0,2,0.34

In [29]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [30]:
def linear_regression(xi):
    result = w0
    
    for j in range(len(w)):
        result = result + xi[j] * w[j]
        
    return result

In [31]:
def logistic_regression(xi):
    score = w0
    
    for j in range(len(w)):
        score = score + xi[j] * w[j]
        
    result = sigmoid(score)
    return result

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)

In [34]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [35]:
# bias term

model.intercept_[0]

np.float64(-0.010838978497809288)

In [36]:
# weights

model.coef_[0].round(3)

array([-0.   , -0.001,  0.007, -0.003, -0.008, -0.006, -0.   , -0.003,
       -0.001, -0.002, -0.002, -0.002, -0.001,  0.137,  0.011,  0.   ,
       -0.009,  0.007, -0.014,  0.009, -0.004,  0.   , -0.002, -0.002,
       -0.001, -0.003, -0.004,  0.054])

In [37]:
y_pred = model.predict_proba(X_val)[:, 1]

In [38]:
decision = (y_pred >= 0.5)

### Accuracy

In [39]:
result = (y_val == decision).mean()

In [40]:
from decimal import Decimal, ROUND_HALF_UP

print(Decimal(result).quantize(
    Decimal("0.01"),
    rounding=ROUND_HALF_UP
))

0.65

## Question 5

In [41]:
dict(zip(dv.get_feature_names_out(), model.coef_[0].round(3)))

{'annual_income': np.float64(-0.0),
 'employment_status=0': np.float64(-0.001),
 'employment_status=employed': np.float64(0.007),
 'employment_status=self_employed': np.float64(-0.003),
 'employment_status=student': np.float64(-0.008),
 'employment_status=unemployed': np.float64(-0.006),
 'industry=0': np.float64(-0.0),
 'industry=education': np.float64(-0.003),
 'industry=finance': np.float64(-0.001),
 'industry=healthcare': np.float64(-0.002),
 'industry=manufacturing': np.float64(-0.002),
 'industry=retail': np.float64(-0.002),
 'industry=technology': np.float64(-0.001),
 'interaction_count': np.float64(0.137),
 'lead_score': np.float64(0.011),
 'lead_source=0': np.float64(0.0),
 'lead_source=events': np.float64(-0.009),
 'lead_source=organic_search': np.float64(0.007),
 'lead_source=paid_ads': np.float64(-0.014),
 'lead_source=referral': np.float64(0.009),
 'lead_source=social_media': np.float64(-0.004),
 'location=0': np.float64(0.0),
 'location=africa': np.float64(-0.002),
 'location=asia': np.float64(-0.002),
 'location=europe': np.float64(-0.001),
 'location=north_america': np.float64(-0.003),
 'location=south_america': np.float64(-0.004),
 'number_of_courses_viewed': np.float64(0.054)}

In [42]:
# note that initially we didn't round the training data, hence not rewriting the training code here.

In [43]:
exclusion_columns = ['lead_source', 'number_of_courses_viewed', 'interaction_count']
all_columns = categorical + numerical

In [44]:
all_columns

['lead_source',
 'industry',
 'employment_status',
 'location',
 'annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score']

In [51]:
dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient = 'records')
X_train = dv.fit_transform(train_dict)
val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict_proba(X_val)[:, 1]
decision = (y_pred >= 0.5)
result_without_elimination = (y_val == decision).mean()

print(f"{col} excluded.")
print(result_without_elimination)

interaction_count excluded.
0.645

In [54]:
# from sklearn.feature_extraction import DictVectorizer

# exclusion_columns = ['lead_source', 'number_of_courses_viewed', 'interaction_count']
# all_columns = categorical + numerical

for col in exclusion_columns:

    training_columns = [i for i in all_columns if i != col]
    

    dv = DictVectorizer(sparse=False)

    train_dict = df_train[training_columns].to_dict(orient = 'records')
    X_train = dv.fit_transform(train_dict)
    val_dict = df_val[training_columns].to_dict(orient='records')
    X_val = dv.transform(val_dict)

    model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict_proba(X_val)[:, 1]
    decision = (y_pred >= 0.5)
    result = (y_val == decision).mean()

    print(f"{col} excluded.")
    print(result)
    print(f"Difference from original score: {result_without_elimination - result}")
    print()

lead_source excluded.
0.642
Difference from original score: 0.0030000000000000027

number_of_courses_viewed excluded.
0.643
Difference from original score: 0.0020000000000000018

interaction_count excluded.
0.601
Difference from original score: 0.04400000000000004

number_of_courses_viewed has smallest difference.

## Question 6

In [55]:
c_values = [0.000001, 0.00001, 0.0001, 0.001]

In [62]:
dicts_full_train = df_full_train[categorical + numerical].to_dict(orient='records')

dv = DictVectorizer(sparse=False)
X_full_train = dv.fit_transform(dicts_full_train)

y_full_train = y_full_train.values

In [63]:
df_full_train.columnsmodel = LogisticRegression(solver='lbfgs')
model.fit(X_full_train, y_full_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [64]:
dicts_test = df_test[categorical + numerical].to_dict(orient='records')
X_test = dv.transform(dicts_test)

y_pred = model.predict_proba(X_test)[:, 1]
decision = (y_pred >= 0.5)
(decision == y_test).mean()

np.float64(0.67)

In [68]:
for c_val in c_values:
    dicts_full_train = df_full_train[categorical + numerical].to_dict(orient='records')

    dv = DictVectorizer(sparse=False)
    X_full_train = dv.fit_transform(dicts_full_train)

    # y_full_train = y_full_train.values
    
    df_full_train.columnsmodel = LogisticRegression(solver='lbfgs', C=c_val)
    model.fit(X_full_train, y_full_train)

    dicts_test = df_test[categorical + numerical].to_dict(orient='records')
    X_test = dv.transform(dicts_test)

    y_pred = model.predict_proba(X_test)[:, 1]
    decision = (y_pred >= 0.5)
    result_cval = (decision == y_test).mean()

    print(c_val)
    # print(result_cval)
    print(Decimal(result_cval).quantize(
    Decimal("0.0000000001"),
    rounding=ROUND_HALF_UP
    ))
    print()

1e-06
0.6700000000

1e-05
0.6700000000

0.0001
0.6700000000

0.001
0.6700000000